### ISSUE TITLE
Only 10 Tasks shown

### ISSUE THREAD

**Issue by tibor78** [e1fueg0/intellij-gitea-plugin#9]
Hi, the plugin works great but currently shows only 10 tasks (issues) and i cant get the tasks i need to work on. (need #1, but only 10,11,12,... are showing)

Is there a way to add search functionality? 
For example, when clicking in Intellij Editor on Tasks, then Open Tasks, now shows 10 items, we are able to type search keywords above and it searches in listed 10 tasks, but it would be nice if it could search in Gitea Issues for the keyword that was typed.

Additionally, is there a way to filter for tasks assigned to me? (no point in showing whole project tasks)

Also can we change the amount of items listed? from default 10 to any number.

**Comment by e1fueg0** [comment]
Very useful features, just implemented them.

Thx @tibor78 for reporting them.
